import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import logger from "../modules/logger/logger";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  logger.info('asdf')

  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>

      <footer className={styles.footer}>
          Powered by
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
      </footer>
    </div>
  );
};

export async function getServerSideProps() {
  logger.info("logging..");
  return {
    props: {},
  };
}

export default Home
